# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('ref', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('credit', models.CharField(max_length=200)),
                ('debit', models.CharField(max_length=200)),
                ('txn', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
            ],
        ),
    ]
